CREATE TABLE USER (
	ID IDENTITY PRIMARY KEY,
	USERNAME VARCHAR NOT NULL,
	PASSWORD VARCHAR NOT NULL
);

CREATE TABLE ROLE (
	ID IDENTITY PRIMARY KEY,
	ROLE VARCHAR NOT NULL
);

CREATE TABLE USER_ROLES (
	USER_ID BIGINT NOT NULL,
	ROLE_ID BIGINT NOT NULL
);
ALTER TABLE USER_ROLES ADD FOREIGN KEY (USER_ID) REFERENCES USER;
ALTER TABLE USER_ROLES ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE;

CREATE TABLE GAME (
	ID IDENTITY PRIMARY KEY,
	NAME VARCHAR NOT NULL
);

CREATE TABLE EXPANSION (
	ID IDENTITY PRIMARY KEY,
	NAME VARCHAR NOT NULL,
	GAME_ID BIGINT NOT NULL
);
ALTER TABLE EXPANSION ADD FOREIGN KEY (GAME_ID) REFERENCES GAME;

CREATE TABLE CARD (
	ID IDENTITY PRIMARY KEY,
	NAME VARCHAR NOT NULL,
	EXPANSION_ID BIGINT NOT NULL
);
ALTER TABLE CARD ADD FOREIGN KEY (EXPANSION_ID) REFERENCES EXPANSION;

CREATE TABLE STOCK (
	ID IDENTITY PRIMARY KEY,
	CONDITION VARCHAR DEFAULT 'UK',
	PREMIUM BOOLEAN DEFAULT FALSE,
	ON_HAND INT DEFAULT 0,
	PRICE NUMERIC(17, 4) DEFAULT 0.0,
	CARD_ID BIGINT NOT NULL
);
ALTER TABLE STOCK ADD FOREIGN KEY (CARD_ID) REFERENCES CARD;

CREATE TABLE DATA_FEED (
	ID IDENTITY PRIMARY KEY,
	NAME VARCHAR NOT NULL,
	VERSION VARCHAR NOT NULL DEFAULT '0.0',
	LAST_UPDATED TIMESTAMP,
	GAME_ID BIGINT NOT NULL
);
ALTER TABLE DATA_FEED ADD FOREIGN KEY (GAME_ID) REFERENCES GAME;