CREATE TABLE USER (
	ID IDENTITY PRIMARY KEY,
	USERNAME VARCHAR NOT NULL,
	PASSWORD VARCHAR NOT NULL
);

CREATE TABLE ROLE (
	ID IDENTITY PRIMARY KEY,
	ROLE VARCHAR NOT NULL
);

CREATE TABLE USER_ROLES (
	USER_ID BIGINT NOT NULL,
	ROLE_ID BIGINT NOT NULL
);
ALTER TABLE USER_ROLES ADD FOREIGN KEY (USER_ID) REFERENCES USER;
ALTER TABLE USER_ROLES ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE;